clear
clc

testDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testDir);

addpath(fullfile(projectRoot, 'configs'));

beforeFiles = dir(projectRoot);
beforeNames = sort({beforeFiles.name});

config = formal_nsga2_config(projectRoot);

assert(isstruct(config), 'Config should be a struct.');

requiredTopFields = {'experiment', 'paths', 'dataset', 'random', ...
    'algorithm', 'energy', 'output'};
for i = 1:numel(requiredTopFields)
    fieldName = requiredTopFields{i};
    assert(isfield(config, fieldName), ...
        ['Formal config missing top-level field: ', fieldName]);
end

requiredExperimentFields = {'name', 'description', 'runType'};
for i = 1:numel(requiredExperimentFields)
    fieldName = requiredExperimentFields{i};
    assert(isfield(config.experiment, fieldName), ...
        ['Formal config experiment missing field: ', fieldName]);
    assert(~isempty(config.experiment.(fieldName)), ...
        ['Formal config experiment field is empty: ', fieldName]);
end
assert(strcmp(config.experiment.runType, 'formal'), ...
    'Formal config runType should be formal.');

requiredPathFields = {'fjsp', 'machineExcel', 'agvExcel', ...
    'algorithmDir', 'outputBaseDir'};
for i = 1:numel(requiredPathFields)
    fieldName = requiredPathFields{i};
    assert(isfield(config.paths, fieldName), ...
        ['Formal config paths missing field: ', fieldName]);
    assert(ischar(config.paths.(fieldName)) || isstring(config.paths.(fieldName)), ...
        ['Formal config path should be text: ', fieldName]);
    assert(~isempty(config.paths.(fieldName)), ...
        ['Formal config path is empty: ', fieldName]);
end

assert(isfile(config.paths.fjsp), 'Configured .fjs file does not exist.');
assert(isfile(config.paths.machineExcel), ...
    'Configured machine Excel file does not exist.');
assert(isfile(config.paths.agvExcel), ...
    'Configured AGV Excel file does not exist.');
assert(isfolder(config.paths.algorithmDir), ...
    'Configured algorithm directory does not exist.');
expectedOutputBaseDir = fullfile(projectRoot, 'outputs', 'formal_nsga2');
assert(strcmp(config.paths.outputBaseDir, expectedOutputBaseDir), ...
    'Formal outputBaseDir should be outputs/formal_nsga2.');

requiredDatasetFields = {'name', 'source', 'note'};
for i = 1:numel(requiredDatasetFields)
    fieldName = requiredDatasetFields{i};
    assert(isfield(config.dataset, fieldName), ...
        ['Formal config dataset missing field: ', fieldName]);
    assert(~isempty(config.dataset.(fieldName)), ...
        ['Formal config dataset field is empty: ', fieldName]);
end

requiredRandomFields = {'seed', 'seedList', 'currentSeed'};
for i = 1:numel(requiredRandomFields)
    fieldName = requiredRandomFields{i};
    assert(isfield(config.random, fieldName), ...
        ['Formal config random missing field: ', fieldName]);
    assert(isnumeric(config.random.(fieldName)) && ...
        all(isfinite(config.random.(fieldName)(:))), ...
        ['Formal config random field should contain finite numbers: ', fieldName]);
end
assert(any(config.random.seedList == config.random.currentSeed), ...
    'Formal config currentSeed should be included in seedList.');

requiredAlgorithmFields = {'name', 'pop', 'max_gen', 'p_cross', 'p_mutation'};
for i = 1:numel(requiredAlgorithmFields)
    fieldName = requiredAlgorithmFields{i};
    assert(isfield(config.algorithm, fieldName), ...
        ['Formal config algorithm missing field: ', fieldName]);
    assert(~isempty(config.algorithm.(fieldName)), ...
        ['Formal config algorithm field is empty: ', fieldName]);
end
assert(config.algorithm.pop > 0 && config.algorithm.pop == floor(config.algorithm.pop), ...
    'Formal config algorithm pop should be a positive integer.');
assert(config.algorithm.max_gen > 0 && ...
    config.algorithm.max_gen == floor(config.algorithm.max_gen), ...
    'Formal config algorithm max_gen should be a positive integer.');
assert(config.algorithm.p_cross >= 0 && config.algorithm.p_cross <= 1, ...
    'Formal config algorithm p_cross should be between 0 and 1.');
assert(config.algorithm.p_mutation >= 0 && config.algorithm.p_mutation <= 1, ...
    'Formal config algorithm p_mutation should be between 0 and 1.');

assert(isfield(config.energy, 'AGVEG_MAX'), ...
    'Formal config energy missing AGVEG_MAX.');
assert(isfield(config.energy, 'eChargeSpeed'), ...
    'Formal config energy missing eChargeSpeed.');
assert(config.energy.AGVEG_MAX > 0, ...
    'Formal config energy AGVEG_MAX should be positive.');
assert(config.energy.eChargeSpeed > 0, ...
    'Formal config energy eChargeSpeed should be positive.');

requiredOutputFields = {'saveSummary', 'saveMat', 'saveRunInfo', 'saveLog'};
for i = 1:numel(requiredOutputFields)
    fieldName = requiredOutputFields{i};
    assert(isfield(config.output, fieldName), ...
        ['Formal config output missing field: ', fieldName]);
    assert(islogical(config.output.(fieldName)) || ...
        isnumeric(config.output.(fieldName)), ...
        ['Formal config output field should be logical-like: ', fieldName]);
end

afterFiles = dir(projectRoot);
afterNames = sort({afterFiles.name});
assert(isequal(beforeNames, afterNames), ...
    'test_formal_nsga2_config created or removed files in the project root.');

fprintf(['test_formal_nsga2_config passed: runType=%s, pop=%d, ', ...
    'max_gen=%d, currentSeed=%g\n'], ...
    config.experiment.runType, ...
    config.algorithm.pop, ...
    config.algorithm.max_gen, ...
    config.random.currentSeed);
