clear
clc

testDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testDir);

addpath(fullfile(projectRoot, 'src', 'cancellation'));

config = make_config(true, 0, 0, Inf);

decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(false), ...
    make_evaluation(true, 0.20, 0, 0), make_evaluation(false, NaN, NaN, NaN), ...
    config);
assert_decision(decision, true, 'local_repair', ...
    'local_stable_enough', false);

decision = select_hybrid_cancellation_policy( ...
    make_candidate(false), make_candidate(true), ...
    make_evaluation(false, NaN, NaN, NaN), make_evaluation(true, 0.30, -1, -2), ...
    config);
assert_decision(decision, true, 'complete_rescheduling', ...
    'local_infeasible_trigger_complete', true);

decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(true), ...
    make_evaluation(true, 0.60, 0, 0), make_evaluation(true, 0.20, -3, -4), ...
    config);
assert_decision(decision, true, 'complete_rescheduling', ...
    'complete_better_Y', true);

decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(true), ...
    make_evaluation(true, 0.10, 0, 0), make_evaluation(true, 0.50, -3, -4), ...
    config);
assert_decision(decision, true, 'local_repair', ...
    'local_better_Y', true);

decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(true), ...
    make_evaluation(true, 0.40, 0, 0), make_evaluation(true, 0.40, -3, -4), ...
    config);
assert_decision(decision, true, 'local_repair', ...
    'tie_break_local', true);

decision = select_hybrid_cancellation_policy( ...
    make_candidate(false), make_candidate(false), ...
    make_evaluation(false, NaN, NaN, NaN), make_evaluation(false, NaN, NaN, NaN), ...
    config);
assert_decision(decision, false, '', 'both_infeasible', false);

thresholdConfig = make_config(false, 0, 0, Inf);
decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(true), ...
    make_evaluation(true, 0.60, 1, -1), make_evaluation(true, 0.20, -3, -4), ...
    thresholdConfig);
assert_decision(decision, true, 'complete_rescheduling', ...
    'threshold_trigger_complete', true);
assert(decision.threshold_report.cmax_delta_triggered, ...
    'Cmax threshold should be triggered.');

thresholdConfig = make_config(false, 2, 0, Inf);
decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(true), ...
    make_evaluation(true, 0.60, 1, -1), make_evaluation(true, 0.20, -3, -4), ...
    thresholdConfig);
assert_decision(decision, true, 'local_repair', ...
    'local_stable_enough', false);
assert(~decision.threshold_report.cmax_delta_triggered, ...
    'Cmax threshold should not be triggered after raising config threshold.');

decision = select_hybrid_cancellation_policy( ...
    make_candidate(true), make_candidate(false), ...
    make_evaluation(true, 0.60, 1, -1), make_evaluation(false, NaN, NaN, NaN), ...
    make_config(true, 0, 0, Inf));
assert_decision(decision, true, 'local_repair', ...
    'complete_triggered_but_infeasible', true);

fprintf('test_order_cancellation_hybrid_policy passed\n');

function candidate = make_candidate(isFeasible)
candidate = struct();
candidate.isFeasible = isFeasible;
candidate.machineTable = {};
candidate.AGVTable = {};
end

function evaluation = make_evaluation(isFeasible, yValue, cmaxDelta, energyDelta)
evaluation = struct();
evaluation.strategyName = '';
evaluation.metrics = struct();
evaluation.metrics.isFeasible = isFeasible;
evaluation.metrics.Y = yValue;
evaluation.metrics.Cmax_delta = cmaxDelta;
evaluation.metrics.energy_delta = energyDelta;
evaluation.report = struct();
evaluation.report.rejectedReasons = {};
end

function config = make_config(useYSelection, cmaxThreshold, ...
    energyThreshold, idleWasteThreshold)
config = struct();
config.hybrid_policy = struct();
config.hybrid_policy.enable_complete_if_local_infeasible = true;
config.hybrid_policy.use_stage_e_y_selection = useYSelection;
config.hybrid_policy.cmax_delta_threshold = cmaxThreshold;
config.hybrid_policy.energy_delta_threshold = energyThreshold;
config.hybrid_policy.idle_waste_threshold = idleWasteThreshold;
config.hybrid_policy.threshold_validation_status = ...
    'pending_stage_l_validation';
end

function assert_decision(decision, expectedIsSelected, ...
    expectedStrategy, expectedReason, expectedTriggeredComplete)
assert(decision.isSelected == expectedIsSelected, ...
    'decision.isSelected mismatch.');
assert(strcmp(decision.selected_strategy, expectedStrategy), ...
    'decision.selected_strategy mismatch.');
assert(strcmp(decision.reason, expectedReason), ...
    'decision.reason mismatch.');
assert(decision.triggered_complete_rescheduling == ...
    expectedTriggeredComplete, ...
    'decision.triggered_complete_rescheduling mismatch.');
assert(isfield(decision, 'local_repair_evaluation'), ...
    'local evaluation should be recorded.');
assert(isfield(decision, 'complete_rescheduling_evaluation'), ...
    'complete evaluation should be recorded.');
end
