clear
clc

testDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testDir);

addpath(fullfile(projectRoot, 'configs'));

beforeFiles = dir(projectRoot);
beforeNames = sort({beforeFiles.name});

config = small_nsga2_config(projectRoot);

assert(isstruct(config), 'Config should be a struct.');
assert(isfield(config, 'paths'), 'Config is missing paths.');
assert(isfield(config, 'random'), 'Config is missing random.');
assert(isfield(config, 'algorithm'), 'Config is missing algorithm.');
assert(isfield(config, 'energy'), 'Config is missing energy.');

requiredPathFields = {'fjsp', 'machineExcel', 'agvExcel', ...
    'algorithmDir', 'outputBaseDir'};
for i = 1:numel(requiredPathFields)
    fieldName = requiredPathFields{i};
    assert(isfield(config.paths, fieldName), ...
        ['Config paths missing field: ', fieldName]);
    assert(ischar(config.paths.(fieldName)) || isstring(config.paths.(fieldName)), ...
        ['Config path should be text: ', fieldName]);
    assert(~isempty(config.paths.(fieldName)), ...
        ['Config path is empty: ', fieldName]);
end

assert(isfile(config.paths.fjsp), 'Configured .fjs file does not exist.');
assert(isfile(config.paths.machineExcel), ...
    'Configured machine Excel file does not exist.');
assert(isfile(config.paths.agvExcel), ...
    'Configured AGV Excel file does not exist.');
assert(isfolder(config.paths.algorithmDir), ...
    'Configured algorithm directory does not exist.');

requiredAlgorithmFields = {'pop', 'max_gen', 'p_cross', 'p_mutation'};
for i = 1:numel(requiredAlgorithmFields)
    fieldName = requiredAlgorithmFields{i};
    assert(isfield(config.algorithm, fieldName), ...
        ['Config algorithm missing field: ', fieldName]);
    assert(isnumeric(config.algorithm.(fieldName)) && ...
        isscalar(config.algorithm.(fieldName)) && ...
        isfinite(config.algorithm.(fieldName)), ...
        ['Config algorithm field should be a finite number: ', fieldName]);
end

assert(config.algorithm.pop > 0 && config.algorithm.pop == floor(config.algorithm.pop), ...
    'Config algorithm pop should be a positive integer.');
assert(config.algorithm.max_gen > 0 && ...
    config.algorithm.max_gen == floor(config.algorithm.max_gen), ...
    'Config algorithm max_gen should be a positive integer.');
assert(config.algorithm.p_cross >= 0 && config.algorithm.p_cross <= 1, ...
    'Config algorithm p_cross should be between 0 and 1.');
assert(config.algorithm.p_mutation >= 0 && config.algorithm.p_mutation <= 1, ...
    'Config algorithm p_mutation should be between 0 and 1.');

assert(isfield(config.random, 'seed'), 'Config random missing seed.');
assert(isnumeric(config.random.seed) && isscalar(config.random.seed) && ...
    isfinite(config.random.seed), 'Config random seed should be a finite number.');

assert(isfield(config.energy, 'AGVEG_MAX'), 'Config energy missing AGVEG_MAX.');
assert(isfield(config.energy, 'eChargeSpeed'), ...
    'Config energy missing eChargeSpeed.');
assert(config.energy.AGVEG_MAX > 0, ...
    'Config energy AGVEG_MAX should be positive.');
assert(config.energy.eChargeSpeed > 0, ...
    'Config energy eChargeSpeed should be positive.');

afterFiles = dir(projectRoot);
afterNames = sort({afterFiles.name});
assert(isequal(beforeNames, afterNames), ...
    'test_small_nsga2_config created or removed files in the project root.');

fprintf(['test_small_nsga2_config passed: pop=%d, max_gen=%d, ', ...
    'seed=%g\n'], ...
    config.algorithm.pop, ...
    config.algorithm.max_gen, ...
    config.random.seed);
