clear
clc

testDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testDir);

addpath(fullfile(projectRoot, 'configs'));
addpath(fullfile(projectRoot, 'src', 'data'));
addpath(fullfile(projectRoot, 'src', 'encoding'));
addpath(fullfile(projectRoot, 'src', 'search'));

config = small_nsga2_config(projectRoot);
rng(config.random.seed);

beforeFiles = dir(projectRoot);
beforeNames = sort({beforeFiles.name});

problem = read_fjsp(config.paths.fjsp);
machineData = read_machine_data(config.paths.machineExcel, problem.machineNum);
agvData = read_agv_data(config.paths.agvExcel);

options = struct();
options.useRefactoredVariation = true;

[NSGA2_Result, chrom, runInfo] = run_nsga2_with_encoding( ...
    config, problem, machineData, agvData, options);

operaNum = sum(problem.operaNumVec);
dim = 5 * operaNum;
assert(size(chrom, 1) == config.algorithm.pop, ...
    'Initial population size does not match pop.');
assert(size(chrom, 2) == dim, ...
    'Initial chromosome length does not match 5 * operaNum.');
assert(runInfo.encodingReport.isValid, ...
    'Initial population generated by encoding layer is invalid.');
assert(runInfo.useRefactoredVariation, ...
    'Test should use refactored variation.');

assert(isfield(NSGA2_Result, 'obj_matrix'), ...
    'NSGA2_Result.obj_matrix is missing.');
assert(~isempty(NSGA2_Result.obj_matrix), ...
    'NSGA2_Result.obj_matrix is empty.');
assert(size(NSGA2_Result.obj_matrix, 2) == 2, ...
    'NSGA2_Result.obj_matrix should contain two objectives.');
assert(all(isfinite(NSGA2_Result.obj_matrix(:))), ...
    'NSGA2_Result.obj_matrix contains non-finite values.');

assert(isfield(NSGA2_Result, 'curve'), 'NSGA2_Result.curve is missing.');
assert(isfield(NSGA2_Result.curve, 'min'), ...
    'NSGA2_Result.curve.min is missing.');
assert(size(NSGA2_Result.curve.min, 2) == config.algorithm.max_gen, ...
    'NSGA2_Result.curve.min column count does not match max_gen.');
assert(all(isfinite(NSGA2_Result.curve.min(:))), ...
    'NSGA2_Result.curve.min contains non-finite values.');

afterFiles = dir(projectRoot);
afterNames = sort({afterFiles.name});
assert(isequal(beforeNames, afterNames), ...
    'test_small_nsga2_refactored_encoding created or removed files in the project root.');

fprintf(['test_small_nsga2_refactored_encoding passed: ', ...
    'paretoSolutionCount=%d, bestMakespan=%.6f, ', ...
    'bestTotalEnergy=%.6f\n'], ...
    size(NSGA2_Result.obj_matrix, 1), ...
    min(NSGA2_Result.obj_matrix(:, 1)), ...
    min(NSGA2_Result.obj_matrix(:, 2)));
