clear
clc

testDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(testDir);

addpath(fullfile(projectRoot, 'src', 'data'));
addpath(fullfile(projectRoot, 'raw_code', 'NSGA-II'));

rng(42);

beforeFiles = dir(projectRoot);
beforeNames = sort({beforeFiles.name});

problem = read_fjsp(fullfile(projectRoot, 'data_sample', 'Mk01.fjs'));
machineData = read_machine_data( ...
    fullfile(projectRoot, 'data_sample', '机器数据.xlsx'), ...
    problem.machineNum);
agvData = read_agv_data(fullfile(projectRoot, 'data_sample', 'AGV数据.xlsx'));

distance_matrix = machineData.distance_matrix;
machineEnergy = machineData.machineEnergy;
AGVEnergy = agvData.AGVEnergy;

AGVEG_MAX = 100;
eChargeSpeed = 20;
distance_MAX = max([max(distance_matrix.machine_to_machine(:)), ...
    max(distance_matrix.load_to_machine), ...
    max(distance_matrix.machine_to_unload), ...
    distance_matrix.load_to_unload]);
AGVEG_MIN = distance_MAX / agvData.AGVSpeed(end) * ...
    (AGVEnergy.free(end) + AGVEnergy.load(end)) + 1e-6;

p_cross = 0.8;
p_mutation = 0.2;
pop = 10;
max_gen = 2;
speedNum = length(agvData.AGVSpeed);
operaNum = sum(problem.operaNumVec);
dim = 5 * operaNum;

chrom = init(pop, problem.jobNum, problem.operaNumVec, ...
    problem.candidateMachine, agvData.AGVNum, speedNum);

assert(size(chrom, 1) == pop, 'Initial population size does not match pop.');
assert(size(chrom, 2) == dim, 'Chromosome length does not match 5 * operaNum.');

NSGA2_Result = NSGA2(p_cross, p_mutation, pop, chrom, max_gen, ...
    problem.jobNum, ...
    problem.jobInfo, ...
    problem.operaNumVec, ...
    problem.machineNum, ...
    agvData.AGVNum, ...
    agvData.AGVSpeed, ...
    problem.candidateMachine, ...
    distance_matrix, ...
    machineEnergy, ...
    AGVEnergy, ...
    AGVEG_MAX, ...
    AGVEG_MIN, ...
    eChargeSpeed);

assert(isfield(NSGA2_Result, 'obj_matrix'), ...
    'NSGA2_Result.obj_matrix is missing.');
assert(~isempty(NSGA2_Result.obj_matrix), ...
    'NSGA2_Result.obj_matrix is empty.');
assert(size(NSGA2_Result.obj_matrix, 2) == 2, ...
    'NSGA2_Result.obj_matrix should contain two objectives.');
assert(all(isfinite(NSGA2_Result.obj_matrix(:))), ...
    'NSGA2_Result.obj_matrix contains non-finite values.');

assert(isfield(NSGA2_Result, 'curve'), 'NSGA2_Result.curve is missing.');
assert(isfield(NSGA2_Result.curve, 'min'), ...
    'NSGA2_Result.curve.min is missing.');
assert(~isempty(NSGA2_Result.curve.min), ...
    'NSGA2_Result.curve.min is empty.');
assert(size(NSGA2_Result.curve.min, 2) == max_gen, ...
    'NSGA2_Result.curve.min column count does not match max_gen.');
assert(all(isfinite(NSGA2_Result.curve.min(:))), ...
    'NSGA2_Result.curve.min contains non-finite values.');

afterFiles = dir(projectRoot);
afterNames = sort({afterFiles.name});
assert(isequal(beforeNames, afterNames), ...
    'test_small_nsga2 created or removed files in the project root.');

fprintf(['test_small_nsga2 passed: paretoSolutionCount=%d, ', ...
    'bestMakespan=%.6f, bestTotalEnergy=%.6f\n'], ...
    size(NSGA2_Result.obj_matrix, 1), ...
    min(NSGA2_Result.obj_matrix(:, 1)), ...
    min(NSGA2_Result.obj_matrix(:, 2)));
